### ISSUE TITLE
I can't get the code under Quick Start to work

### ISSUE THREAD

**Issue by JohnReinhold** [jscarle/OnePassword.NET#61]
I'm making an extension for Business Central, where I at one point need to read information from an item in 1Password. So I began creating a simple console exe for Windows, coded in c#, using your wrapper. And I followed your example under Quick Start. This is my current code:

```
var options = new OnePassword.OnePasswordManagerOptions();
options.Path = "c:\\Program Files\\1Password CLI\\";
options.Verbose = true;
var op = new OnePassword.OnePasswordManager(options);

var domain = "xxxxxxx.1password.eu";
op.UseAccount(domain);
var my1password = "yyyyyyy";
op.SignIn(my1password);

//onePasswordMgt.SignOut();

var vaults = op.GetVaults();
```

Running this, makes 1Password on my workstation prompt for my password, that are enteret without error.

It fails at op.GetVaults(); with **Cannot execute command because account has not been signed in**. Using verbose, the console shows my this: **op signin --force --raw --format json --no-color --account xxxxxxx.1password.eu**. I tried running with a signout right after signin. And I get the same error. So I'm kind a stuck here.

I'm using CLI version 2.24.0,OnePassword.NET 2.3.2.0 and .NET 8.

I can get it to work using PowerShell only. But that's not my favorite method.

Any ideas?

**Comment by jscarle** [comment]
Hi John,

I'm going to do some testing on my end to see if anything's changed. I'll get back to you soon.

**Comment by jscarle** [comment]
After looking into your issue, I discovered there was an error with the SignOut command, which I fixed. A new version has been published, v2.3.3.

A couple of notes regarding signing in and signing out.

If you want to write automation that will run on a server or in a pipeline, I recommend you do the following steps on every run.
```csharp
onePassword.AddAccount(domain, email, secretKey, password);
onePassword.SignIn(password);
// Do work
onePassword.SignOut();
onePassword.Forget();
```

Accounts are stored in the environment by the CLI and the environments gets wiped between builds since they tend to run on different servers.

If you're confident that your environment will preserve the account information, you could do something along the lines of:

```csharp
var accounts = OnePassword.GetAccounts();
if (accounts.Count == 0)
    onePassword.AddAccount(domain, email, secretKey, password);
onePassword.SignIn(password);
// Do work
onePassword.SignOut();
```

Let me know if you still have issues. And thanks for bringing this up.

**Comment by JohnReinhold** [comment]
Yes, the issue is still there.
I did this code:

```
var options = new OnePassword.OnePasswordManagerOptions();
options.Path = "c:\\Program Files\\1Password CLI\\";
options.Verbose = true;
var op = new OnePassword.OnePasswordManager(options);

var domain = "xxxx.1password.eu";
var email = "yyy@xxx.com";
var secretKey = "A3-blabla";
var password = "ppp";

op.AddAccount(domain, email, secretKey, password);
op.SignIn(password);
var vaults = op.GetVaults();
```

It prompts me for login to 1password, and the it fails at the GetVaults() line. It also fails if I change the last line to SignOut().
The console output:
<img width="857" alt="image" src="https://github.com/jscarle/OnePassword.NET/assets/9877709/b99537c9-c28e-488b-8875-c480272fa6db">

(greetings from Denmark)
